-- FUEL-130 — kettlebell swings replace the Tue/Thu skipping session.
--
-- Schema, then data, in one file because the data needs the schema.
--
-- ## The columns
--
-- `training_template_entries.valid_from` / `valid_until` are the dates a row
-- schedules on, inclusive, null meaning open. Every existing row is open at
-- both ends, so it resolves exactly as it did. They exist because a past date
-- is RESOLVED against the template rather than read back from a log: the
-- adherence grid, /training's Recent and past dates, and the week export all
-- ask the template what 3 September held. Repointing Tuesday in place would
-- answer with today's workout and orphan every skipping log.
--
-- `workout_exercises.target_total_reps` is the swings' 75, which is not a set
-- count. `takes_load` marks the exercise whose sets write
-- `exercise_sets.load_kg`, dormant since 0008 and first written here.
--
-- All four are additive: null, or false by default, which is what every
-- existing row means. The code already deployed selects explicit columns and
-- never names them.
--
-- ## The data
--
-- For every user whose Tue/Thu is still the open-ended skipping session:
--
--   1. a Kettlebell Swings workout,
--   2. its exercises, as `src/lib/seed/workouts.ts` defines them,
--   3. its template rows, on the same weekdays and in the same sort order,
--      open from the day this runs IN THAT USER'S TIMEZONE,
--   4. the skipping rows closed the day before — only where step 3 put a
--      replacement beside them, so a user is never left with neither,
--   5. the intervals slot time copied to the kettlebell one.
--
-- NOTHING IS DELETED OR RENAMED. The skipping workout keeps its id, name, type
-- and exercises, so every log, set and export line that points at it still
-- reads "Skipping Intervals + Core", and still costs at the rope's MET band.
--
-- Idempotent: each step is guarded on its own result, so a re-run finds the
-- workout, the exercises and the rows already there and the skipping rows
-- already closed, and changes nothing. Every user, owner and demo alike, as
-- 0011 did — a demo's library is the same seed's.
--
-- The literals below are generated by `src/lib/seed/kettlebell-backfill.ts`,
-- and `kettlebell-backfill.test.ts` fails if they stop matching the seed.
-- The seed is authoritative from here on; these are this migration's record
-- of what it wrote.
--
-- Matched by name AND type, because `workouts` has no stable key column: the
-- seed's key never reaches the database.

ALTER TABLE "training_template_entries" ADD COLUMN "valid_from" date;--> statement-breakpoint
ALTER TABLE "training_template_entries" ADD COLUMN "valid_until" date;--> statement-breakpoint
ALTER TABLE "workout_exercises" ADD COLUMN "target_total_reps" integer;--> statement-breakpoint
ALTER TABLE "workout_exercises" ADD COLUMN "takes_load" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "training_template_entries" ADD CONSTRAINT "training_template_entries_valid_range" CHECK ("valid_from" is null or "valid_until" is null or "valid_from" <= "valid_until");--> statement-breakpoint
ALTER TABLE "workout_exercises" ADD CONSTRAINT "workout_exercises_target_total_reps" CHECK ("target_total_reps" is null
          or ("target_total_reps" between 1 and 19980 and "target_seconds_low" is null));
--> statement-breakpoint

-- 1. The workout, once per user whose Tue/Thu is still skipping.
INSERT INTO "workouts" ("user_id", "name", "type", "description", "rotation_group", "rotation_index")
SELECT DISTINCT e."user_id", v.name, v.type, v.description, NULL::text, NULL::integer
FROM "training_template_entries" e
JOIN "workouts" s ON s."id" = e."workout_id" AND s."user_id" = e."user_id"
CROSS JOIN (VALUES
('Kettlebell Swings', 'kettlebell', '### Format

After the warm-up: 75 two-handed swings in total. If 75 in a row isn''t
there yet, do sets — anything from 10 to 25 — with about 60 sec rest
between them, until the total reaches 75.

### The swing

A hip hinge, not a squat. Hinge back with a flat back until the bell is
between the thighs, then pop the hips forward and squeeze the glutes hard
at the top. The bell floats to about chest height on straight arms — not
overhead. Shoulders never go in front of the knees at the bottom.

### No core finisher

The plank, dead bug and side plank that followed the skipping went with
it. The swing is itself a posterior-chain and anti-extension movement —
the plank at the top of every rep — so the session is the swings alone,
as the source prescribes it.')
) AS v(name, type, description)
WHERE
  s."name" = 'Skipping Intervals + Core'
  AND s."type" = 'intervals'
  AND e."valid_until" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "workouts" k
    WHERE k."user_id" = e."user_id" AND k."type" = 'kettlebell' AND k."name" = v.name
  );
--> statement-breakpoint

-- 2. Its exercises, for a kettlebell session that has none yet.
--
-- Every column cast: a column that is null in every VALUES row is typed
-- `text` by Postgres, which will not insert into an integer column.
INSERT INTO "workout_exercises" (
  "user_id", "workout_id", "sort_order", "name", "prescription", "section", "notes",
  "target_sets", "target_reps_low", "target_reps_high",
  "target_seconds_low", "target_seconds_high", "target_total_reps", "takes_load"
)
SELECT
  k."user_id", k."id", x.sort_order::integer, x.name::text, x.prescription::text,
  x.section::text, x.notes::text,
  x.target_sets::integer, x.target_reps_low::integer, x.target_reps_high::integer,
  x.target_seconds_low::integer, x.target_seconds_high::integer,
  x.target_total_reps::integer, x.takes_load::boolean
FROM "workouts" k
CROSS JOIN (VALUES
  (0, 'Joint prep', '~2 min', 'warmup', '10 arm circles forward, 10 backward, 10 shoulder rolls, 5 slow torso twists each side.', null, null, null, null, null, null, false),
  (1, 'Hinge prep', '~3 min', 'warmup', '10 slow hip hinges with hands on the hips, 10 glute bridges, 10 bodyweight squats, then 5 easy swings.', null, null, null, null, null, null, false),
  (2, 'Kettlebell swings', '75 swings — sets of 10–25, ~60 s rest, until 75', 'work', 'Two hands. Hinge, snap the hips, squeeze the glutes; the bell floats to chest height.', null, 10, 25, null, null, 75, true),
  (3, 'Posterior-chain stretches', '30 sec each', 'cooldown', 'Hamstring stretch and figure-four glute stretch, each leg, then a kneeling hip-flexor stretch.', null, null, null, null, null, null, false),
  (4, 'Upper-body stretches', '30 sec each', 'cooldown', 'Chest doorway stretch, then child''s pose.', null, null, null, null, null, null, false)
) AS x(
  sort_order, name, prescription, section, notes,
  target_sets, target_reps_low, target_reps_high,
  target_seconds_low, target_seconds_high, target_total_reps, takes_load
)
WHERE
  k."type" = 'kettlebell'
  AND k."name" = 'Kettlebell Swings'
  AND NOT EXISTS (SELECT 1 FROM "workout_exercises" we WHERE we."workout_id" = k."id");
--> statement-breakpoint

-- 3. The swings' template rows, open from today in the user's own timezone —
-- the day the owner chose (the day this is applied), and "today" is only
-- meaningful in the zone the rest of the app resolves dates in.
INSERT INTO "training_template_entries" (
  "user_id", "day_of_week", "workout_id", "rotation_group", "sort_order", "valid_from"
)
SELECT
  e."user_id", e."day_of_week", k."id", NULL::text, e."sort_order",
  (now() AT TIME ZONE p."timezone")::date
FROM "training_template_entries" e
JOIN "workouts" s ON s."id" = e."workout_id" AND s."user_id" = e."user_id"
JOIN "workouts" k
  ON k."user_id" = e."user_id" AND k."type" = 'kettlebell' AND k."name" = 'Kettlebell Swings'
JOIN "profiles" p ON p."user_id" = e."user_id"
WHERE
  s."name" = 'Skipping Intervals + Core'
  AND s."type" = 'intervals'
  AND e."valid_until" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "training_template_entries" n
    WHERE n."user_id" = e."user_id" AND n."day_of_week" = e."day_of_week"
      AND n."workout_id" = k."id"
  );
--> statement-breakpoint

-- 4. The skipping rows closed the day before — where, and only where, a
-- swings row now opens on that weekday. A user step 3 could not serve (no
-- profile, so no timezone) keeps skipping rather than losing the day.
UPDATE "training_template_entries" AS e
SET "valid_until" = n."valid_from" - 1
FROM "workouts" s, "workouts" k, "training_template_entries" n
WHERE
  s."id" = e."workout_id"
  AND s."user_id" = e."user_id"
  AND s."name" = 'Skipping Intervals + Core'
  AND s."type" = 'intervals'
  AND e."valid_until" IS NULL
  AND k."user_id" = e."user_id"
  AND k."type" = 'kettlebell'
  AND k."name" = 'Kettlebell Swings'
  AND n."user_id" = e."user_id"
  AND n."workout_id" = k."id"
  AND n."day_of_week" = e."day_of_week"
  AND n."valid_from" IS NOT NULL;
--> statement-breakpoint

-- 5. The session's time of day moves with it. `workout_times` is keyed by
-- type, and /settings now offers `kettlebell` where it offered `intervals`;
-- a stored intervals time with no kettlebell one is copied across, and the
-- intervals key is left where it is.
UPDATE "profiles"
SET "workout_times" = "workout_times" || jsonb_build_object('kettlebell', "workout_times" -> 'intervals')
WHERE
  jsonb_typeof("workout_times") = 'object'
  AND "workout_times" ? 'intervals'
  AND NOT ("workout_times" ? 'kettlebell');
