import type {
  MealSlot,
  NewMeal,
  NewMealIngredient,
  NewWorkout,
  NewWorkoutExercise,
} from "@/lib/db/schema";
import type { DayOfWeek } from "@/lib/date";

/**
 * The shape of the committed seed libraries — PRD § P7 → repository privacy.
 *
 * Recipes and workout definitions are food and exercises, so they ship in git.
 * Body metrics do not: no weight, target, macro goal or measurement appears in
 * this directory, and `scripts/check-no-metrics.sh` (FUEL-16) is what keeps that
 * true rather than this comment.
 *
 * ## Why these are not just `NewMeal` / `NewWorkout`
 *
 * Two columns cannot exist in a committed file:
 *
 * 1. `userId` — seed data is loaded for whoever is being seeded. The owner's
 *    script (FUEL-15) and the demo provisioner (FUEL-41) both read these same
 *    arrays and supply their own id, which is the entire reason one library can
 *    serve both without the demo ever touching an owner row.
 * 2. `id` — generated by the database on insert. A committed uuid would be the
 *    same uuid in every demo session, and the composite foreign keys in
 *    schema.ts are the only thing standing between that and a cross-tenant read.
 *
 * So each seed type omits both and adds `key`: a stable, human-readable slug
 * that survives the insert. Template entries (FUEL-15, FUEL-41) need to say
 * "Tuesday dinner is the chilli" without knowing the generated uuid, and a slug
 * is what lets the loader build its own key → uuid map at insert time.
 */

/** A stable identifier for a seed row, used to wire template entries to it. */
export type SeedKey = string;

/* -------------------------------------------------------------------------- */
/* Meals                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * One ingredient line.
 *
 * `grams` is nullable and genuinely used: "salt and pepper to taste" has no
 * weight, and `meal_ingredients.grams` was made nullable precisely so the seed
 * would not have to invent one. `nonScaleMeasure` is the measure actually used
 * in the kitchen — the PRD's owner does not own a scale, so for P8 the cup /
 * spoon / handful string is the load-bearing one and grams is the hint.
 */
export type SeedIngredient = Omit<
  NewMealIngredient,
  "id" | "userId" | "mealId" | "sortOrder"
>;

/**
 * One recipe.
 *
 * `ingredients` may be empty. That is not an oversight — PRD § Risks commits to
 * "schema accepts a meal with macros and no ingredient rows, so P8 can be seeded
 * later without blocking P1–P6", and this type is where that promise is kept.
 * P1–P6 read only the macros; P8 (FUEL-44) is the only consumer of this array.
 */
export type SeedMeal = Omit<NewMeal, "id" | "userId"> & {
  key: SeedKey;
  ingredients: readonly SeedIngredient[];
};

/* -------------------------------------------------------------------------- */
/* Workouts                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * One exercise line. `prescription` is displayed verbatim and never parsed —
 * '3 x 12' and '30s on / 30s off' are the same kind of thing to this app.
 */
export type SeedExercise = Omit<
  NewWorkoutExercise,
  "id" | "userId" | "workoutId" | "sortOrder"
>;

/**
 * One session.
 *
 * `rotationGroup` / `rotationIndex` move together or not at all — the schema's
 * `workouts_rotation_pair` check enforces it, and `rotationWorkout()` in
 * rotation.ts resolves A/B by taking the elapsed-session count modulo the number
 * of workouts sharing a group. A walk names neither and is scheduled by a fixed
 * `workout_id` instead.
 */
export type SeedWorkout = Omit<NewWorkout, "id" | "userId"> & {
  key: SeedKey;
  exercises: readonly SeedExercise[];
};

/* -------------------------------------------------------------------------- */
/* The weekly template                                                        */
/* -------------------------------------------------------------------------- */

/**
 * One recurring meal slot — "Tuesday dinner is the chicken and rice".
 *
 * ## Why the weekly template is committed, when body metrics are not
 *
 * PRD § P7 draws the line at *personal data*, not at everything the owner does:
 * the demo "shares the plan's *shape* — same recipe library, same training
 * structure — but is an invented person with different body metrics". Which
 * recipe lands on which weekday is that shape. It reveals no weight, no target
 * and no measurement, so it ships in git alongside the recipes it names, and
 * FUEL-41's demo provisioner reads the same arrays rather than restating them.
 *
 * The gitignored half is only what the PRD actually calls personal: the profile
 * row and the weigh-in history. See `scripts/seed-local.example.ts`.
 *
 * `mealKey` rather than a uuid, for the reason given at the top of this file —
 * ids are generated at insert time, and a committed uuid would be the same uuid
 * in every demo session. `loadSeedLibraries` builds the key → uuid map.
 */
export type SeedPlanEntry = {
  dayOfWeek: DayOfWeek;
  slot: MealSlot;
  mealKey: SeedKey;

  /** Ordering within a slot that holds more than one meal — the two snacks. */
  sortOrder?: number;
};

/**
 * One recurring training slot.
 *
 * A row names EITHER a fixed workout (the daily walk) OR a rotation group
 * (Circuit A/B, resolved per date from `programStartDate`). The schema makes
 * that exclusive with the `training_template_entries_target` check; the union
 * below makes it a compile error instead, so a malformed entry is caught while
 * editing this file rather than as a constraint violation partway through a
 * seed run against a real database.
 */
export type SeedTrainingEntry = { dayOfWeek: DayOfWeek; sortOrder?: number } & (
  | { workoutKey: SeedKey; rotationGroup?: never }
  | { rotationGroup: string; workoutKey?: never }
);

/**
 * The rotation group the bodyweight circuits alternate within.
 *
 * Named once, here, rather than spelled as a string literal at each use.
 * `rotation_group` is free text in the schema, and rotation.ts documents that a
 * group nobody belongs to resolves to nothing at all — a typo between the
 * workout row and the template row would therefore schedule silence, with no
 * error anywhere. One constant makes that a compile error instead.
 */
export const BODYWEIGHT_CIRCUIT = "bodyweight-circuit";
